name: Test

on: [ push, pull_request ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macOS-latest ]
    steps:
      - uses: actions/checkout@v2

      # Install required tools
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'

      # Run tests
      - name: Tests on macOS, Linux
        run: ./gradlew clean test
        if: runner.os != 'Windows'
      - name: Tests on Windows
        run: ./gradlew.bat clean test
        if: runner.os == 'Windows'